# Generated by Django 2.2.7 on 2020-05-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200503_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.Player'),
        ),
    ]
